const name_to_table = {
  "aaron lan": 8,
  "aaron ma": 14,
  "adrienne wong": 8,
  "aerin yim": 22,
  "agnes zhu": 23,
  "alessandro louly": 3,
  "sandro louly": 3,
  "alex yu": 13,
  "allison chien": 3,
  "andrew bryson": 11,
  "andrew tang": 25,
  "andrew tso": 11,
  "andy wong": 8,
  "angelo zhu": 23,
  "anthony rachmat": 23,
  "ariana moniaga": 21,
  "avery chien": 3,
  "benson wan": 9,
  "bethany kim": 16,
  "bok yeung": 16,
  "brandon tang": 25,
  "breanna le": 5,
  "brett nakashima": 9,
  "brooklyn wong": 8,
  "caleb kim": 24,
  "caleb yuan": 3,
  "calvin chien": 4,
  "cheryl tang": 25,
  "christie chen": 5,
  "chris gee": 7,
  "cindy chen": 6,
  "claire payne": 2,
  "danica advincula": 11,
  "daniel lai": 25,
  "daniel wesley serna": 15,
  "danielle huang": 22,
  "daryl moniaga": 21,
  "david wu": 1,
  "dean syn": 1,
  "debbie wang": 4,
  "devin oyetibo": 13,
  "donna lee": 10,
  "shelley kim": 11,
  "dustin fong": 23,
  "dylan chao": 18,
  "elias choi": 18,
  "emily chan": 15,
  "emma chen": 6,
  "eric gin": 20,
  "eric kuo": 6,
  "eric wong": 12,
  "erica seid": 21,
  "erika uychocde": 11,
  "esther de la cruz": 24,
  "ethan choi": 18,
  "ethan lee": 13,
  "ethan sandoval": 5,
  "eunice luk": 12,
  "florence mathews": 7,
  "fred chen": 6,
  "george wang": 4,
  "george wu": 24,
  "georgie mathews": 7,
  "gong gong luk": 12,
  "grace fernandes": 17,
  "h rebecca peng": 10,
  "rebecca peng": 10,
  "hannah akahoshi": 13,
  "hannah chong": 1,
  "hannah de la cruz": 3,
  "helen syn": 1,
  "helen wu": 1,
  "henry liu": 2,
  "hsiu-chin wang": 2,
  "hsiu-lan chen": 2,
  "jacoby chung": 17,
  "jake deverian": 3,
  "james yim": 24,
  "jason choi": 18,
  "jay de la cruz": 22,
  "jed shank": 3,
  "jen choi": 18,
  "jenny gi": 14,
  "jenny liu": 2,
  "jeremy wong": 7,
  "jim shank": 4,
  "jimmy jin": 13,
  "joel huang": 10,
  "john mcclain": 14,
  "john jae lee": 9,
  "johnny wong": 14,
  "jonathan lin": 20,
  "joon yim": 22,
  "jordan chung": 17,
  "joseph yim": 7,
  "joseph zhu": 21,
  "joshua de la cruz": 24,
  "joshua wong": 12,
  "joyce rhee": 19,
  "jude chung": 17,
  "justin folk": 21,
  "kaitlyn zhang": 9,
  "kalize munakata": 8,
  "kara wu": 19,
  "karen chien": 4,
  "karen siu": 16,
  "karen yim": 22,
  "katelyn tong": 15,
  "katia shank": 3,
  "katrina pan": 5,
  "keith yeung": 16,
  "kelly dekitani": 13,
  "kenny siu": 16,
  "kim ramos": 5,
  "kim wong": 2,
  "kim ting": 16,
  "kimberly ting": 16,
  "kobe ing": 18,
  "kristin akioka": 15,
  "kyle deguzman": 7,
  "lawrence wu": 19,
  "linh de la cruz": 22,
  "lisa miao": 12,
  "luke chao": 24,
  "madison tang": 25,
  "manuel pelayo": 11,
  "margaret chao": 1,
  "mark kaneshiro": 20,
  "mark lim": 17,
  "mark wu": 16,
  "mason hardy": 23,
  "matt chan": 9,
  "matt chong": 1,
  "matt kim": 16,
  "megan eng": 15,
  "megan lee": 15,
  "mi tian": 14,
  "michelle shank": 4,
  "miguel solis": 13,
  "mikayla wu": 19,
  "mike tang": 25,
  "miriam gin": 20,
  "moonli kuo": 6,
  "na luk": 12,
  "nadia wong": 14,
  "naomi wu": 19,
  "naomi yung": 21,
  "nathan kim": 7,
  "nathan zhang": 9,
  "nick huynh": 25,
  "nicole fong": 18,
  "nicole fukuyama": 9,
  "noah chen": 6,
  "noel takaya": 15,
  "nyssa situ": 9,
  "odelia hui": 15,
  "omar espinosa": 23,
  "patricia lee": 14,
  "paul lee": 10,
  "peter nguyen": 25,
  "peter yim": 22,
  "peter yuan": 2,
  "quinn malloy": 19,
  "rachel wong": 8,
  "ray tai": 4,
  "raymond chao": 1,
  "ray chao": 1,
  "riley gin": 20,
  "riley seid": 21,
  "robert chu": 23,
  "rossesti wong": 12,
  "ruby gin": 20,
  "ryan d'innocenzo": 7,
  "ryan tong": 20,
  "noobydud": 20,
  "sam leong": 21,
  "samantha reed": 24,
  "sarah kang": 18,
  "seth gerdine": 17,
  "sijii wu": 19,
  "simon wang": 12,
  "solomon cheung": 20,
  "stephanie munakata": 8,
  "steve gi": 14,
  "steven huang": 22,
  "steven wong": 2,
  "sue chuang": 10,
  "susanna eng": 5,
  "tasha obert": 19,
  "thomas kaneshige": 23,
  "tiffany chao": 5,
  "tim chung": 17,
  "tony reksoatmodjo": 11,
  "tristan chao": 24,
  "trudy liu": 4,
  "valerie ma": 14,
  "weila shen": 10,
  "winnie zhang": 10,
  "wonchan kim": 13,
  "y peter peng": 10,
  "yinting tso": 11,
  "younghae chung": 17,
  "zaiden munakata": 8,
  
  // Alternative name mappings (short/long forms)"
  "christopher gee": 7, // alt for chris gee
  "matthew chan": 9, // alt for matt chan
  "matthew chong": 1, // alt for matt chong
  "matthew kim": 16, // alt for matt kim
  "michael tang": 25, // alt for mike tang
  "stephen gi": 14, // alt for steve gi
  "steven gi": 14, // alt for steve gi
  "timothy chung": 17, // alt for tim chung
  "jacob deverian": 3, // alt for jake deverian
  "james jin": 13, // alt for jimmy jin
  "jennifer gi": 14, // alt for jenny gi
  "jennifer liu": 2, // alt for jenny liu
  "anthony reksoatmodjo": 11, // alt for tony reksoatmodjo
  "susan chuang": 10, // alt for sue chuang
  "samuel leong": 21, // alt for sam leong
  "james shank": 4, // alt for jim shank
  "nicholas huynh": 25, // alt for nick huynh
  "joe yim": 7, // alt for joseph yim
  "joey yim": 7, // alt for joseph yim
  "joe zhu": 21, // alt for joseph zhu
  "josh de la cruz": 24, // alt for joshua de la cruz
  "josh wong": 12, // alt for joshua wong
  "dan wesley serna": 15, // alt for daniel wesley serna
  "daniel serna": 15, // alt for daniel wesley serna
  "dan serna": 15, // alt for daniel wesley serna
  "steve huang": 22, // alt for steven huang
  "steve wong": 2, // alt for steven wong,
  "peter peng": 10, // alt for y peter peng,
};

const table_to_pokemon = {
  1: "Pikachu",
  2: "Eevee",
  3: "Spheal",
  4: "Snorlax",
  5: "Hoothoot",
  6: "Slowpoke",
  7: "Squirtle",
  8: "Plusle",
  9: "Dugtrio",
  10: "Starly",
  11: "Lechonk",
  12: "Mareep",
  13: "Porygon",
  14: "Rockruff",
  15: "Tandemaus",
  16: "Morpeko",
  17: "Larvitar",
  18: "Froakie",
  19: "Drifloon",
  20: "Riolu",
  21: "Lapras",
  22: "Cyndaquil",
  23: "Piplup",
  24: "Houndour",
  25: "Ralts",
};

const pokemon_to_id = {
  "Pikachu": 25,
  "Eevee": 133,
  "Spheal": 363,
  "Snorlax": 143,
  "Hoothoot": 163,
  "Slowpoke": 79,
  "Squirtle": 7,
  "Plusle": 311,
  "Dugtrio": 51,
  "Starly": 396,
  "Lechonk": 915,
  "Mareep": 179,
  "Porygon": 137,
  "Rockruff": 744,
  "Tandemaus": 924,
  "Larvitar": 246,
  "Froakie": 656,
  "Drifloon": 425,
  "Riolu": 447,
  "Lapras": 131,
  "Cyndaquil": 155,
  "Piplup": 393,
  "Houndour": 228,
  "Ralts": 280
}
