const name_to_table = {
  "Aaron Lan": 8,
  "Aaron Ma": 14,
  "Adrienne (Mei Mei) Wong": 8,
  "Aerin Yim": 22,
  "Agnes Zhu": 23,
  "Alessandro Louly": 3,
  "Alex Yu": 13,
  "Allison Chien": 3,
  "Andrew Bryson": 11,
  "Andrew Tang": 25,
  "Andrew Tso": 11,
  "Andy Wong": 8,
  "Angelo Zhu": 23,
  "Anthony Rachmat": 23,
  "Ariana Moniaga": 21,
  "Avery Chien": 3,
  "Benson Wan": 9,
  "Bethany Kim": 16,
  "Bok Yeung": 16,
  "Brandon Tang": 25,
  "Breanna Le": 5,
  "Brett Nakashima": 9,
  "Brooklyn Wong": 8,
  "Caleb Kim": 24,
  "Caleb Yuan": 3,
  "Calvin Chien": 4,
  "Cheryl Tang": 25,
  "Christie Chen": 5,
  "Christopher Gee": 7,
  "Cindy Chen": 6,
  "Claire Payne": 2,
  "Danica Advincula": 11,
  "Daniel Lai": 25,
  "Daniel Wesley Serna": 15,
  "Danielle Huang": 22,
  "Daryl Moniaga": 21,
  "David Wu": 1,
  "Dean Syn": 1,
  "Debbie Wang": 4,
  "Devin Oyetibo": 13,
  "Donna Lee": 10,
  "Dowon(Shelley) Kim": 11,
  "Dustin Fong": 23,
  "Dylan Chao": 18,
  "Elias Choi": 18,
  "Emily Chan": 15,
  "Emma Chen": 6,
  "Eric Gin": 20,
  "Eric Kuo": 6,
  "Eric Wong": 12,
  "Erica Seid": 21,
  "Erika Uychocde": 11,
  "Esther De La Cruz": 24,
  "Ethan Choi": 18,
  "Ethan Lee": 13,
  "Ethan Sandoval": 5,
  "Eunice Luk": 12,
  "Florence Mathews": 7,
  "Fred Chen": 6,
  "George Wang": 4,
  "George Wu": 24,
  "Georgie Mathews": 7,
  "Gong gong Luk": 12,
  "Grace Fernandes": 17,
  "H Rebecca Peng": 10,
  "Hannah Akahoshi": 13,
  "Hannah Chong": 1,
  "Hannah De La Cruz": 3,
  "Helen Syn": 1,
  "Helen Wu": 1,
  "Henry Liu": 2,
  "Hsiu-Chin Wang": 2,
  "Hsiu-Lan Chen": 2,
  "Jacoby Chung": 17,
  "Jake Deverian": 3,
  "James Yim": 24,
  "Jason Choi": 18,
  "Jay De La Cruz": 22,
  "Jedidiah Shank": 3,
  "Jen Choi": 18,
  "Jenny Gi": 14,
  "Jenny Liu": 2,
  "Jeremy Wong": 7,
  "Jim Shank": 4,
  "Jimmy Jin": 13,
  "Joel Huang": 10,
  "John McClain": 14,
  "John Jae Lee": 9,
  "Johnny Wong": 14,
  "Jonathan Lin": 20,
  "Joon Yim": 22,
  "Jordan Chung": 17,
  "Joseph Yim": 7,
  "Joseph Zhu": 21,
  "Joshua De La Cruz": 24,
  "Joshua Wong": 12,
  "Joyce Rhee": 19,
  "Jude Chung": 17,
  "Justin Folk": 21,
  "Kaitlyn Zhang": 9,
  "Kalize Munakata": 8,
  "Kara Wu": 19,
  "Karen Chien": 4,
  "Karen Siu": 16,
  "Karen Yim": 22,
  "Katelyn Tong": 15,
  "Katia Shank": 3,
  "Katrina Pan": 5,
  "Keith Yeung": 16,
  "Kelly Dekitani": 13,
  "Kenny Siu": 16,
  "Kim Ramos": 5,
  "Kim Wong": 2,
  "Kimberly Ting": 16,
  "Kobe Ing": 18,
  "Kristin Akioka": 15,
  "Kyle DeGuzman": 7,
  "Lawrence Wu": 19,
  "Linh De La Cruz": 22,
  "Lisa Miao": 12,
  "Luke Chao": 24,
  "Madison Tang": 25,
  "Manuel Pelayo": 11,
  "Margaret Chao": 1,
  "Mark Kaneshiro": 20,
  "Mark Lim": 17,
  "Mark Wu": 16,
  "Mason Hardy": 23,
  "Matt Chan": 9,
  "Matt Chong": 1,
  "Matt Kim": 16,
  "Megan Eng": 15,
  "Megan Lee": 15,
  "Mi Tian": 14,
  "Michelle Shank": 4,
  "Miguel Solis": 13,
  "Mikayla Wu": 19,
  "Mike Tang": 25,
  "Miriam Gin": 20,
  "Moonli Kuo": 6,
  "Na Luk": 12,
  "Nadia Wong": 14,
  "Naomi Wu": 19,
  "Naomi Yung": 21,
  "Nathan Kim": 7,
  "Nathan Zhang": 9,
  "Nick Huynh": 25,
  "Nicole Fong": 18,
  "Nicole Fukuyama": 9,
  "Noah Chen": 6,
  "Noel Takaya": 15,
  "Nyssa Situ": 9,
  "Odelia Hui": 15,
  "Omar Espinosa": 23,
  "Patricia Lee": 14,
  "Paul Lee": 10,
  "Peter Nguyen": 25,
  "Peter Yim": 22,
  "Peter Yuan": 2,
  "Quinn Malloy": 19,
  "Rachel Wong": 8,
  "Ray Tai": 4,
  "Raymond Chao": 1,
  "Riley Gin": 20,
  "Riley Seid": 21,
  "Robert Chu": 23,
  "Rossesti Wong": 12,
  "Ruby Gin": 20,
  "Ryan D'Innocenzo": 7,
  "Ryan Tong": 20,
  "Sam Leong": 21,
  "Samantha Reed": 24,
  "Sarah Kang": 18,
  "Seth Gerdine": 17,
  "Sijii Wu": 19,
  "Simon Wang (Lisa's Husband)": 12,
  "Solomon Cheung": 20,
  "Stephanie Munakata": 8,
  "Steve Gi": 14,
  "Steven Huang": 22,
  "Steven Wong": 2,
  "Sue Chuang": 10,
  "Susanna Eng": 5,
  "Tasha Obert": 19,
  "Thomas Kaneshige": 23,
  "Tiffany Chao": 5,
  "Tim Chung": 17,
  "Tony Reksoatmodjo": 11,
  "Tristan Chao": 24,
  "Trudy Liu": 4,
  "Valerie Ma": 14,
  "Weila Shen": 10,
  "Winnie Zhang": 10,
  "Wonchan Kim": 13,
  "Y Peter Peng": 10,
  "Yinting Tso": 11,
  "Younghae Chung": 17,
  "Zaiden Munakata": 8,
};

const table_to_pokemon = {
  1: "Pikachu",
  2: "Eevee",
  3: "Spheal",
  4: "Snorlax",
  5: "Hoothoot",
  6: "Slowpoke",
  7: "Squirtle",
  8: "Plusle",
  9: "Dugtrio",
  10: "Starly",
  11: "Lechonk",
  12: "Mareep",
  13: "Porygon",
  14: "Rockruff",
  15: "Tandemaus",
  16: "Morpeko",
  17: "Larvitar",
  18: "Froakie",
  19: "Drifloon",
  20: "Riolu",
  21: "Lapras",
  22: "Cyndaquil",
  23: "Piplup",
  24: "Houndour",
  25: "Ralts",
};
